In [138]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [139]:
R_sales = pd.read_csv('../Data/Raw/sales_raw.csv')
R_sales.head()

,transaction_id,date,store,category,unit_price,quantity,customer_age,payment_method
0,TXN115708,2024-01-30,Store_C_PortHarcourt,Home_Goods,12732.62,3,NaN,CASH
1,TXN109445,2023-08-27,Store_D_Kano,Groceries,3320.91,4,69.0,Transfer
2,TXN123657,2024-08-14,Store_D_Kano,Groceries,2649.43,8,29.0,Card
3,TXN113862,2023-12-15,Store_E_Ibadan,Groceries,NaN,1,38.0,CASH
4,TXN106755,2023-06-20,Store_E_Ibadan,Electronics,46741.91,2,41.0,Cash

In [140]:
R_sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 29647 entries, 0 to 29646
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  29647 non-null  str
 1   date            29647 non-null  str
 2   store           29647 non-null  str
 3   category        29647 non-null  str
 4   unit_price      29054 non-null  str
 5   quantity        29647 non-null  int64
 6   customer_age    26681 non-null  float64
 7   payment_method  29647 non-null  str
dtypes: float64(1), int64(1), str(6)
memory usage: 1.8 MB

In [141]:
R_sales.isnull().sum()

transaction_id       0
date                 0
store                0
category             0
unit_price         593
quantity             0
customer_age      2966
payment_method       0
dtype: int64

Null Values are found in unit_price and customer age

In [142]:
R_sales.duplicated().sum()

np.int64(270)

There are 270 duplicate values

In [143]:
R_sales.columns

Index(['transaction_id', 'date', 'store', 'category', 'unit_price', 'quantity',
       'customer_age', 'payment_method'],
      dtype='str')

In [144]:
R_sales['unit_price'].apply(type).value_counts()

unit_price
<class 'str'>      29054
<class 'float'>      593
Name: count, dtype: int64

In [145]:
R_sales['date'].str.contains('/').sum()

np.int64(1504)

In [146]:
R_sales['payment_method'].unique()

<StringArray>
['CASH', 'Transfer', 'Card', 'Cash', 'Card ']
Length: 5, dtype: str

There are two columns named card and also a column of the same name one written in Captial case and the other in smaller  case

In [147]:
R_sales.describe()

           quantity  customer_age
count  29647.000000  26681.000000
mean       7.277161     43.388928
std        4.409178     15.009049
min      -14.000000     18.000000
25%        4.000000     30.000000
50%        7.000000     43.000000
75%       11.000000     56.000000
max       14.000000     69.000000

In [148]:
R_sales['unit_price'].describe()

count       29054
unique      28513
top       2165.46
freq            3
Name: unit_price, dtype: object

In [149]:
R_sales['unit_price'].apply(type)

0          <class 'str'>
1          <class 'str'>
2          <class 'str'>
3        <class 'float'>
4          <class 'str'>
              ...
29642      <class 'str'>
29643      <class 'str'>
29644      <class 'str'>
29645      <class 'str'>
29646      <class 'str'>
Name: unit_price, Length: 29647, dtype: object

In [150]:
import numpy as np

def is_str(val):
    if isinstance(val, str):
        val = val.replace('₦', '').replace(',', '').strip()
        try:
            return float(val)
        except ValueError:
            return np.nan
    return val

R_sales['unit_price'] = R_sales['unit_price'].apply(is_str)

In [151]:
R_sales['unit_price'] = R_sales['unit_price'].apply(is_str)

In [152]:
R_sales['unit_price']

0        12732.62
1         3320.91
2         2649.43
3             NaN
4        46741.91
           ...
29642    11313.00
29643     3262.61
29644    11276.30
29645    48366.32
29646     8052.59
Name: unit_price, Length: 29647, dtype: float64

In [153]:
R_sales[R_sales['date'].str.contains('/')]

,transaction_id,date,store,category,unit_price,quantity,customer_age,payment_method
17,TXN110790,01/10/2023,Store_D_Kano,Apparel,11494.88,7,NaN,Card
91,TXN128195,02/12/2024,Store_D_Kano,Groceries,3664.21,13,42.0,Cash
94,TXN104313,19/04/2023,Store_E_Ibadan,Electronics,49602.49,10,67.0,Transfer
95,TXN106125,04/06/2023,Store_E_Ibadan,Home_Goods,15771.39,4,62.0,Cash
104,TXN101551,10/02/2023,Store_E_Ibadan,Electronics,39101.94,3,27.0,Card
...,...,...,...,...,...,...,...,...
29535,TXN118638,10/04/2024,Store_E_Ibadan,Electronics,44732.94,2,18.0,Cash
29576,TXN121383,18/06/2024,Store_C_PortHarcourt,Beauty,4835.95,10,46.0,Card
29581,TXN112137,03/11/2023,Store_D_Kano,Beauty,5017.67,5,47.0,Card
29612,TXN102692,10/03/2023,Store_D_Kano,Electronics,40746.50,3,49.0,Transfer
29630,TXN101953,20/02/2023,Store_E_Ibadan,Home_Goods,10825.22,11,42.0,CASH

In [186]:
parsed_slash = pd.to_datetime(R_sales['date'], format='%d/%m/%Y', errors='coerce')
parsed_iso = pd.to_datetime(R_sales['date'], format='%Y-%m-%d', errors='coerce')

In [187]:
R_sales['date'] = parsed_slash.fillna(parsed_iso)

In [213]:

R_sales['date'].isnull().sum()

np.int64(0)

In [214]:
R_sales

,transaction_id,date,store,category,unit_price,quantity,customer_age,payment_method,returns,price_outlier
1,TXN109445,2023-08-27,Store_D_Kano,Groceries,3320.91,4,69.0,transfer,Sales,False
2,TXN123657,2024-08-14,Store_D_Kano,Groceries,2649.43,8,29.0,card,Sales,False
4,TXN106755,2023-06-20,Store_E_Ibadan,Electronics,46741.91,2,41.0,cash,Sales,False
6,TXN128164,2024-12-01,Store_E_Ibadan,Apparel,16237.05,7,42.0,transfer,Sales,False
7,TXN110190,2023-09-16,Store_B_Abuja,Groceries,3310.92,6,58.0,cash,Sales,False
...,...,...,...,...,...,...,...,...,...,...
29642,TXN108527,2023-08-04,Store_C_PortHarcourt,Home_Goods,11313.00,14,43.0,transfer,Sales,False
29643,TXN104714,2023-04-29,Store_B_Abuja,Groceries,3262.61,12,40.0,card,Sales,False
29644,TXN110196,2023-09-16,Store_C_PortHarcourt,Apparel,11276.30,5,25.0,card,Sales,False
29645,TXN108419,2023-08-01,Store_C_PortHarcourt,Electronics,48366.32,4,44.0,card,Sales,False
29646,TXN119145,2024-04-23,Store_C_PortHarcourt,Apparel,8052.59,2,36.0,card,Sales,False

In [215]:
R_sales[R_sales['unit_price'].isnull()]

Empty DataFrame
Columns: [transaction_id, date, store, category, unit_price, quantity, customer_age, payment_method, returns, price_outlier]
Index: []

In [216]:
R_sales=R_sales.dropna(subset=['unit_price'])

In [217]:
R_sales['unit_price']

1         3320.91
2         2649.43
4        46741.91
6        16237.05
7         3310.92
           ...
29642    11313.00
29643     3262.61
29644    11276.30
29645    48366.32
29646     8052.59
Name: unit_price, Length: 25888, dtype: float64

In [218]:
R_sales = R_sales.drop_duplicates(keep='first')

In [219]:
R_sales['returns'] =np.where(R_sales['quantity'] < 0, 'Return','Sales')

In [220]:
R_sales.query('returns == "Return"').head(5)

,transaction_id,date,store,category,unit_price,quantity,customer_age,payment_method,returns,price_outlier
58,TXN106555,2023-06-15,Store_C_PortHarcourt,Electronics,43091.60,-5,37.0,card,Return,False
122,TXN120129,2024-05-18,Store_A_Lagos,Apparel,10262.58,-3,39.0,cash,Return,False
207,TXN122730,2024-07-23,Store_C_PortHarcourt,Home_Goods,11198.43,-1,18.0,cash,Return,False
394,TXN110191,2023-09-16,Store_B_Abuja,Groceries,2810.59,-9,65.0,card,Return,False
454,TXN111218,2023-10-12,Store_C_PortHarcourt,Home_Goods,13558.54,-5,18.0,card,Return,False

In [221]:
R_sales['payment_method'] = R_sales['payment_method'].str.lower().str.strip()

In [222]:
R_sales['payment_method'].unique()

<StringArray>
['transfer', 'card', 'cash']
Length: 3, dtype: str

In [223]:
R_sales['customer_age'] = R_sales['customer_age'].fillna(R_sales['customer_age'].median())

In [224]:
def flag_outliers(group):
    q1 = group.quantile(0.25)
    q3 = group.quantile(0.75)
    iqr = q3 - q1
    upper_bound = q3 + 3 * iqr   # 3x IQR = strict outlier threshold
    return group > upper_bound

R_sales['price_outlier'] = R_sales.groupby('category')['unit_price'].transform(flag_outliers)
R_sales[R_sales['price_outlier']]   # inspect them

,transaction_id,date,store,category,unit_price,quantity,customer_age,payment_method,returns,price_outlier
647,TXN125968,2024-10-08,Store_A_Lagos,Beauty,438233.0,12,43.0,card,Sales,True
2299,TXN118208,2024-03-31,Store_E_Ibadan,Home_Goods,1696044.0,5,51.0,cash,Sales,True
2860,TXN129294,2024-12-30,Store_B_Abuja,Home_Goods,1509381.0,13,28.0,card,Sales,True
3032,TXN127422,2024-11-14,Store_C_PortHarcourt,Beauty,496176.0,6,26.0,cash,Sales,True
3637,TXN103557,2023-03-31,Store_E_Ibadan,Home_Goods,1366128.0,6,25.0,cash,Sales,True
4153,TXN126283,2024-10-16,Store_D_Kano,Beauty,477616.0,7,44.0,cash,Sales,True
4364,TXN106227,2023-06-07,Store_C_PortHarcourt,Apparel,785124.0,4,33.0,card,Sales,True
5299,TXN100717,2023-01-20,Store_C_PortHarcourt,Electronics,4651974.0,12,20.0,card,Sales,True
6115,TXN114536,2024-01-02,Store_B_Abuja,Home_Goods,1026903.0,12,67.0,transfer,Sales,True
7484,TXN110376,2023-09-21,Store_B_Abuja,Apparel,764629.0,4,48.0,cash,Sales,True
7813,TXN127864,2024-11-25,Store_A_Lagos,Beauty,555273.0,7,42.0,card,Sales,True
8896,TXN119363,2024-04-28,Store_D_Kano,Electronics,5146812.0,12,26.0,card,Sales,True
9358,TXN110757,2023-09-30,Store_D_Kano,Groceries,314375.0,3,57.0,transfer,Sales,True
9414,TXN103733,2023-04-04,Store_E_Ibadan,Apparel,774007.0,2,27.0,transfer,Sales,True
11131,TXN109724,2023-09-04,Store_B_Abuja,Apparel,884812.0,12,54.0,cash,Sales,True
11178,TXN120382,2024-05-24,Store_D_Kano,Beauty,428067.0,9,54.0,card,Sales,True
11259,TXN124679,2024-09-07,Store_E_Ibadan,Beauty,578887.0,11,46.0,card,Sales,True
11282,TXN103944,2023-04-10,Store_B_Abuja,Home_Goods,1223628.0,7,60.0,transfer,Sales,True
11381,TXN121461,2024-06-20,Store_B_Abuja,Apparel,851254.0,9,24.0,transfer,Sales,True
12347,TXN107568,2023-07-10,Store_A_Lagos,Groceries,249589.0,5,52.0,transfer,Sales,True
12415,TXN104298,2023-04-19,Store_B_Abuja,Beauty,494696.0,10,18.0,cash,Sales,True
12589,TXN104045,2023-04-12,Store_D_Kano,Electronics,4077646.0,13,22.0,transfer,Sales,True
13143,TXN128185,2024-12-02,Store_C_PortHarcourt,Home_Goods,1777952.0,2,67.0,card,Sales,True
14462,TXN109222,2023-08-22,Store_A_Lagos,Apparel,770167.0,3,30.0,cash,Sales,True
15071,TXN126102,2024-10-11,Store_C_PortHarcourt,Apparel,848338.0,1,45.0,cash,Sales,True
15263,TXN103178,2023-03-21,Store_E_Ibadan,Home_Goods,1364759.0,8,50.0,card,Sales,True
16420,TXN114033,2023-12-20,Store_B_Abuja,Electronics,6308477.0,9,38.0,cash,Sales,True
17738,TXN105842,2023-05-29,Store_A_Lagos,Home_Goods,1108374.0,11,65.0,card,Sales,True
18308,TXN115535,2024-01-26,Store_C_PortHarcourt,Home_Goods,1230316.0,10,20.0,card,Sales,True
18599,TXN120966,2024-06-08,Store_C_PortHarcourt,Electronics,5392649.0,4,45.0,card,Sales,True
19156,TXN120464,2024-05-26,Store_E_Ibadan,Electronics,5603112.0,10,28.0,card,Sales,True
20070,TXN103005,2023-03-18,Store_A_Lagos,Electronics,6426120.0,8,49.0,cash,Sales,True
20548,TXN128914,2024-12-21,Store_A_Lagos,Home_Goods,2451567.0,7,42.0,cash,Sales,True
20965,TXN122388,2024-07-15,Store_C_PortHarcourt,Electronics,4674490.0,14,48.0,cash,Sales,True
21801,TXN125696,2024-10-02,Store_C_PortHarcourt,Home_Goods,1233338.0,5,28.0,cash,Sales,True
22613,TXN119729,2024-05-08,Store_D_Kano,Beauty,517015.0,13,26.0,cash,Sales,True
22973,TXN114534,2024-01-02,Store_B_Abuja,Apparel,904047.0,6,69.0,card,Sales,True
23128,TXN100979,2023-01-27,Store_B_Abuja,Beauty,422452.0,5,40.0,card,Sales,True
23863,TXN108583,2023-08-05,Store_E_Ibadan,Beauty,670643.0,10,57.0,transfer,Sales,True
24364,TXN126709,2024-10-27,Store_C_PortHarcourt,Groceries,367441.0,2,26.0,card,Sales,True
25041,TXN105870,2023-05-30,Store_A_Lagos,Electronics,5168495.0,7,30.0,card,Sales,True
25648,TXN127992,2024-11-27,Store_D_Kano,Apparel,832682.0,10,37.0,cash,Sales,True
26644,TXN112725,2023-11-18,Store_D_Kano,Groceries,358554.0,5,56.0,card,Sales,True
26782,TXN110112,2023-09-14,Store_D_Kano,Beauty,470752.0,6,52.0,cash,Sales,True
27625,TXN116315,2024-02-14,Store_C_PortHarcourt,Groceries,267672.0,8,28.0,card,Sales,True
27671,TXN103157,2023-03-21,Store_B_Abuja,Groceries,284164.0,14,40.0,card,Sales,True
27916,TXN121820,2024-06-29,Store_E_Ibadan,Beauty,541904.0,8,23.0,card,Sales,True
28354,TXN110246,2023-09-17,Store_E_Ibadan,Home_Goods,1358789.0,10,61.0,card,Sales,True
28695,TXN119358,2024-04-28,Store_D_Kano,Electronics,5905801.0,8,60.0,card,Sales,True
29149,TXN116509,2024-02-18,Store_E_Ibadan,Groceries,344086.0,8,56.0,cash,Sales,True
29333,TXN118022,2024-03-27,Store_C_PortHarcourt,Electronics,4237082.0,4,65.0,cash,Sales,True
29358,TXN116807,2024-02-25,Store_E_Ibadan,Home_Goods,1660771.0,2,63.0,card,Sales,True
29400,TXN114530,2024-01-02,Store_A_Lagos,Beauty,516141.0,6,55.0,transfer,Sales,True

In [229]:
R_sales.groupby('category')['unit_price'].describe()

,count,mean,std,min,25%,50%,75%,max
category,,,,,,,,
Apparel,5085.0,10494.331860,34360.166716,6800.65,7768.2600,8689.710,10031.650,904047.0
Beauty,5254.0,6357.917223,25233.261529,3825.33,4377.4625,4905.005,5729.525,670643.0
Electronics,5173.0,61986.381550,241533.635619,38251.97,43731.5900,49015.500,56851.880,6426120.0
Groceries,5043.0,3270.811039,11644.065032,2125.23,2445.4600,2746.010,3150.930,367441.0
Home_Goods,5333.0,17119.714303,73658.078822,10200.70,11671.4800,13073.010,15041.420,2451567.0

In [232]:
R_sales = R_sales[~R_sales['price_outlier']]

In [233]:
R_sales = R_sales.drop(columns=['price_outlier'])

In [234]:
R_sales.to_csv('../Data/processed/sales_clean.csv', index=False)