In [84]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [85]:
R_sales = pd.read_csv('../Data/Raw/sales_raw.csv')
R_sales.head()

,transaction_id,date,store,category,unit_price,quantity,customer_age,payment_method
0,TXN115708,2024-01-30,Store_C_PortHarcourt,Home_Goods,12732.62,3,NaN,CASH
1,TXN109445,2023-08-27,Store_D_Kano,Groceries,3320.91,4,69.0,Transfer
2,TXN123657,2024-08-14,Store_D_Kano,Groceries,2649.43,8,29.0,Card
3,TXN113862,2023-12-15,Store_E_Ibadan,Groceries,NaN,1,38.0,CASH
4,TXN106755,2023-06-20,Store_E_Ibadan,Electronics,46741.91,2,41.0,Cash

In [86]:
R_sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 29647 entries, 0 to 29646
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  29647 non-null  str
 1   date            29647 non-null  str
 2   store           29647 non-null  str
 3   category        29647 non-null  str
 4   unit_price      29054 non-null  str
 5   quantity        29647 non-null  int64
 6   customer_age    26681 non-null  float64
 7   payment_method  29647 non-null  str
dtypes: float64(1), int64(1), str(6)
memory usage: 1.8 MB

In [87]:
R_sales.isnull().sum()

transaction_id       0
date                 0
store                0
category             0
unit_price         593
quantity             0
customer_age      2966
payment_method       0
dtype: int64

Null Values are found in unit_price and customer age

In [88]:
R_sales.duplicated().sum()

np.int64(270)

There are 270 duplicate values

In [89]:
R_sales.columns

Index(['transaction_id', 'date', 'store', 'category', 'unit_price', 'quantity',
       'customer_age', 'payment_method'],
      dtype='str')

In [90]:
R_sales['unit_price'].apply(type).value_counts()

unit_price
<class 'str'>      29054
<class 'float'>      593
Name: count, dtype: int64

In [91]:
R_sales['date'].str.contains('/').sum()

np.int64(1504)

In [92]:
R_sales['payment_method'].unique()

<StringArray>
['CASH', 'Transfer', 'Card', 'Cash', 'Card ']
Length: 5, dtype: str

There are two columns named card and also a column of the same name one written in Captial case and the other in smaller  case

In [93]:
R_sales.describe()

           quantity  customer_age
count  29647.000000  26681.000000
mean       7.277161     43.388928
std        4.409178     15.009049
min      -14.000000     18.000000
25%        4.000000     30.000000
50%        7.000000     43.000000
75%       11.000000     56.000000
max       14.000000     69.000000

In [94]:
R_sales['unit_price'].describe()

count       29054
unique      28513
top       2165.46
freq            3
Name: unit_price, dtype: object

In [95]:
R_sales['unit_price'].apply(type)

0          <class 'str'>
1          <class 'str'>
2          <class 'str'>
3        <class 'float'>
4          <class 'str'>
              ...
29642      <class 'str'>
29643      <class 'str'>
29644      <class 'str'>
29645      <class 'str'>
29646      <class 'str'>
Name: unit_price, Length: 29647, dtype: object

In [96]:
import numpy as np

def is_str(val):
    if isinstance(val, str):
        val = val.replace('$', '').replace(',', '').strip()
        try:
            return float(val)
        except ValueError:
            return np.nan
    return val

R_sales['unit_price'] = R_sales['unit_price'].apply(is_str)

In [97]:
R_sales['unit_price'] = R_sales['unit_price'].apply(is_str)

In [98]:
R_sales['unit_price']

0        12732.62
1         3320.91
2         2649.43
3             NaN
4        46741.91
           ...
29642    11313.00
29643     3262.61
29644    11276.30
29645    48366.32
29646     8052.59
Name: unit_price, Length: 29647, dtype: float64

In [99]:
R_sales[R_sales['date'].str.contains('/')]

,transaction_id,date,store,category,unit_price,quantity,customer_age,payment_method
17,TXN110790,01/10/2023,Store_D_Kano,Apparel,11494.88,7,NaN,Card
91,TXN128195,02/12/2024,Store_D_Kano,Groceries,3664.21,13,42.0,Cash
94,TXN104313,19/04/2023,Store_E_Ibadan,Electronics,49602.49,10,67.0,Transfer
95,TXN106125,04/06/2023,Store_E_Ibadan,Home_Goods,15771.39,4,62.0,Cash
104,TXN101551,10/02/2023,Store_E_Ibadan,Electronics,39101.94,3,27.0,Card
...,...,...,...,...,...,...,...,...
29535,TXN118638,10/04/2024,Store_E_Ibadan,Electronics,44732.94,2,18.0,Cash
29576,TXN121383,18/06/2024,Store_C_PortHarcourt,Beauty,4835.95,10,46.0,Card
29581,TXN112137,03/11/2023,Store_D_Kano,Beauty,5017.67,5,47.0,Card
29612,TXN102692,10/03/2023,Store_D_Kano,Electronics,40746.50,3,49.0,Transfer
29630,TXN101953,20/02/2023,Store_E_Ibadan,Home_Goods,10825.22,11,42.0,CASH

In [100]:
parsed_iso = pd.to_datetime(R_sales['date'], format='%Y-%m-%d', errors='coerce')

In [101]:
R_sales

,transaction_id,date,store,category,unit_price,quantity,customer_age,payment_method
0,TXN115708,2024-01-30,Store_C_PortHarcourt,Home_Goods,12732.62,3,NaN,CASH
1,TXN109445,2023-08-27,Store_D_Kano,Groceries,3320.91,4,69.0,Transfer
2,TXN123657,2024-08-14,Store_D_Kano,Groceries,2649.43,8,29.0,Card
3,TXN113862,2023-12-15,Store_E_Ibadan,Groceries,NaN,1,38.0,CASH
4,TXN106755,2023-06-20,Store_E_Ibadan,Electronics,46741.91,2,41.0,Cash
...,...,...,...,...,...,...,...,...
29642,TXN108527,2023-08-04,Store_C_PortHarcourt,Home_Goods,11313.00,14,43.0,Transfer
29643,TXN104714,2023-04-29,Store_B_Abuja,Groceries,3262.61,12,40.0,Card
29644,TXN110196,2023-09-16,Store_C_PortHarcourt,Apparel,11276.30,5,25.0,Card
29645,TXN108419,2023-08-01,Store_C_PortHarcourt,Electronics,48366.32,4,44.0,Card
29646,TXN119145,2024-04-23,Store_C_PortHarcourt,Apparel,8052.59,2,36.0,Card

In [102]:
R_sales[R_sales['unit_price'].isnull()]

,transaction_id,date,store,category,unit_price,quantity,customer_age,payment_method
3,TXN113862,2023-12-15,Store_E_Ibadan,Groceries,NaN,1,38.0,CASH
53,TXN100318,2023-01-09,Store_C_PortHarcourt,Beauty,NaN,13,59.0,Cash
60,TXN120054,2024-05-16,Store_B_Abuja,Electronics,NaN,7,NaN,Cash
66,TXN122101,2024-07-07,Store_B_Abuja,Groceries,NaN,5,25.0,Card
75,TXN107889,2023-07-19,Store_B_Abuja,Apparel,NaN,14,51.0,Card
...,...,...,...,...,...,...,...,...
29541,TXN117411,2024-03-12,Store_A_Lagos,Beauty,NaN,2,33.0,Cash
29545,TXN109201,2023-08-21,Store_C_PortHarcourt,Electronics,NaN,5,31.0,Card
29562,TXN104105,2023-04-14,Store_A_Lagos,Electronics,NaN,10,32.0,Card
29586,TXN120609,2024-05-30,Store_B_Abuja,Beauty,NaN,1,23.0,Cash
29628,TXN128802,2024-12-18,Store_B_Abuja,Electronics,NaN,6,NaN,Cash

In [103]:
R_sales=R_sales.dropna(subset=['unit_price'])

In [104]:
R_sales['unit_price']

0        12732.62
1         3320.91
2         2649.43
4        46741.91
5         7085.51
           ...
29642    11313.00
29643     3262.61
29644    11276.30
29645    48366.32
29646     8052.59
Name: unit_price, Length: 28185, dtype: float64

In [ ]:
R_sales = R_sales.drop_duplicates(keep='first')